apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-client
  template:
    metadata:
      labels:
        app: my-app-client
    spec:
      imagePullSecrets: [{"name": "gitlab-registry-{{ CI_PROJECT_ID }}"}]
      containers:
      - name: client
        image: "{{ CI_REGISTRY_IMAGE }}/client:latest"
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "{{ API_URL }}"
        resources:
          limits:
            cpu: 50m
            memory: 256Mi
          requests:
            cpu: 25m
            memory: 50Mi